<?php

namespace App\Models;

enum TransactionType: string
{
    case ADDED_ACTIVITY = 'ADDED_ACTIVITY';
    case REMOVED_ACTIVITY = 'REMOVED_ACTIVITY';
    case RESTORED_ACTIVITY = 'RESTORED_ACTIVITY';
    case ADDED_EXPENSE = 'ADDED_EXPENSE';
    case DELETED_EXPENSE = 'DELETED_EXPENSE';
    case RESTORED_EXPENSE = 'RESTORED_EXPENSE';
    case ADDED_SUBTRIP = 'ADDED_SUBTRIP';
    case DELETED_SUBTRIP = 'DELETED_SUBTRIP';
    case RESTORED_SUBTRIP = 'RESTORED_SUBTRIP';
    case ADDED_FUND_CONTRIBUTION = 'ADDED_FUND_CONTRIBUTION';
    case DELETED_FUND_CONTRIBUTION = 'DELETED_FUND_CONTRIBUTION';
    case RESTORED_FUND_CONTRIBUTION = 'RESTORED_FUND_CONTRIBUTION';
    case SETTLEMENT_PAID = 'SETTLEMENT_PAID';
}