<?php

namespace App\Models;

enum TransactionType: string
{
    case ACTIVITY_ADDED = 'ACTIVITY_ADDED';
    case ACTIVITY_REMOVED = 'ACTIVITY_REMOVED';
    case ACTIVITY_RESTORED = 'ACTIVITY_RESTORED';
    case EXPENSE_ADDED = 'EXPENSE_ADDED';
    case EXPENSE_DELETED = 'EXPENSE_DELETED';
    case EXPENSE_RESTORED = 'EXPENSE_RESTORED';
    case SUBTRIP_ADDED = 'SUBTRIP_ADDED';
    case SUBTRIP_DELETED = 'SUBTRIP_DELETED';
    case SUBTRIP_RESTORED = 'SUBTRIP_RESTORED';
    case FUND_CONTRIBUTION_ADDED = 'FUND_CONTRIBUTION_ADDED';
    case FUND_CONTRIBUTION_DELETED = 'FUND_CONTRIBUTION_DELETED';
    case FUND_CONTRIBUTION_RESTORED = 'FUND_CONTRIBUTION_RESTORED';
}
